# Generated by Django 6.0.2 on 2026-03-02 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('merchant', models.CharField(default='Неизвестно', max_length=255, verbose_name='Магазин/Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='KZT', max_length=10, verbose_name='Валюта')),
                ('transaction_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], default='expense', max_length=10)),
                ('category', models.CharField(choices=[('food', '🍔 Еда'), ('transport', '🚌 Транспорт'), ('shopping', '🛍 Покупки'), ('health', '💊 Здоровье'), ('entertainment', '🎭 Развлечения'), ('salary', '💼 Зарплата'), ('utilities', '🧾 Коммунальные'), ('other', '📦 Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/', verbose_name='Исходный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.FloatField(default=1.0)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.transaction')),
            ],
        ),
    ]
